// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Approbot.proto

#include "Approbot.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace device {
class AppRobotDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<AppRobot>
      _instance;
} _AppRobot_default_instance_;
}  // namespace device
namespace protobuf_Approbot_2eproto {
static void InitDefaultsAppRobot() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::device::_AppRobot_default_instance_;
    new (ptr) ::device::AppRobot();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::device::AppRobot::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_AppRobot =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsAppRobot}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_AppRobot.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::device::AppRobot, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::device::AppRobot, robot_character_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::device::AppRobot)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::device::_AppRobot_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "Approbot.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\016Approbot.proto\022\006device\"#\n\010AppRobot\022\027\n\017"
      "robot_character\030\001 \001(\005b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 69);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Approbot.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_Approbot_2eproto
namespace device {

// ===================================================================

void AppRobot::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int AppRobot::kRobotCharacterFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

AppRobot::AppRobot()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_Approbot_2eproto::scc_info_AppRobot.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:device.AppRobot)
}
AppRobot::AppRobot(const AppRobot& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  robot_character_ = from.robot_character_;
  // @@protoc_insertion_point(copy_constructor:device.AppRobot)
}

void AppRobot::SharedCtor() {
  robot_character_ = 0;
}

AppRobot::~AppRobot() {
  // @@protoc_insertion_point(destructor:device.AppRobot)
  SharedDtor();
}

void AppRobot::SharedDtor() {
}

void AppRobot::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* AppRobot::descriptor() {
  ::protobuf_Approbot_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_Approbot_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const AppRobot& AppRobot::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_Approbot_2eproto::scc_info_AppRobot.base);
  return *internal_default_instance();
}


void AppRobot::Clear() {
// @@protoc_insertion_point(message_clear_start:device.AppRobot)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  robot_character_ = 0;
  _internal_metadata_.Clear();
}

bool AppRobot::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:device.AppRobot)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 robot_character = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &robot_character_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:device.AppRobot)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:device.AppRobot)
  return false;
#undef DO_
}

void AppRobot::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:device.AppRobot)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 robot_character = 1;
  if (this->robot_character() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->robot_character(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:device.AppRobot)
}

::google::protobuf::uint8* AppRobot::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:device.AppRobot)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 robot_character = 1;
  if (this->robot_character() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->robot_character(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:device.AppRobot)
  return target;
}

size_t AppRobot::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:device.AppRobot)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 robot_character = 1;
  if (this->robot_character() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->robot_character());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void AppRobot::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:device.AppRobot)
  GOOGLE_DCHECK_NE(&from, this);
  const AppRobot* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const AppRobot>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:device.AppRobot)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:device.AppRobot)
    MergeFrom(*source);
  }
}

void AppRobot::MergeFrom(const AppRobot& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:device.AppRobot)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.robot_character() != 0) {
    set_robot_character(from.robot_character());
  }
}

void AppRobot::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:device.AppRobot)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AppRobot::CopyFrom(const AppRobot& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:device.AppRobot)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AppRobot::IsInitialized() const {
  return true;
}

void AppRobot::Swap(AppRobot* other) {
  if (other == this) return;
  InternalSwap(other);
}
void AppRobot::InternalSwap(AppRobot* other) {
  using std::swap;
  swap(robot_character_, other->robot_character_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata AppRobot::GetMetadata() const {
  protobuf_Approbot_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_Approbot_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace device
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::device::AppRobot* Arena::CreateMaybeMessage< ::device::AppRobot >(Arena* arena) {
  return Arena::CreateInternal< ::device::AppRobot >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
