// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: orige_message.proto

#ifndef PROTOBUF_INCLUDED_orige_5fmessage_2eproto
#define PROTOBUF_INCLUDED_orige_5fmessage_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_orige_5fmessage_2eproto 

namespace protobuf_orige_5fmessage_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_orige_5fmessage_2eproto
class PciRobotEvent;
class PciRobotEventDefaultTypeInternal;
extern PciRobotEventDefaultTypeInternal _PciRobotEvent_default_instance_;
namespace google {
namespace protobuf {
template<> ::PciRobotEvent* Arena::CreateMaybeMessage<::PciRobotEvent>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class PciRobotEvent : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PciRobotEvent) */ {
 public:
  PciRobotEvent();
  virtual ~PciRobotEvent();

  PciRobotEvent(const PciRobotEvent& from);

  inline PciRobotEvent& operator=(const PciRobotEvent& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PciRobotEvent(PciRobotEvent&& from) noexcept
    : PciRobotEvent() {
    *this = ::std::move(from);
  }

  inline PciRobotEvent& operator=(PciRobotEvent&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PciRobotEvent& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PciRobotEvent* internal_default_instance() {
    return reinterpret_cast<const PciRobotEvent*>(
               &_PciRobotEvent_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(PciRobotEvent* other);
  friend void swap(PciRobotEvent& a, PciRobotEvent& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PciRobotEvent* New() const final {
    return CreateMaybeMessage<PciRobotEvent>(NULL);
  }

  PciRobotEvent* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<PciRobotEvent>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const PciRobotEvent& from);
  void MergeFrom(const PciRobotEvent& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PciRobotEvent* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string equipmentName = 1;
  void clear_equipmentname();
  static const int kEquipmentNameFieldNumber = 1;
  const ::std::string& equipmentname() const;
  void set_equipmentname(const ::std::string& value);
  #if LANG_CXX11
  void set_equipmentname(::std::string&& value);
  #endif
  void set_equipmentname(const char* value);
  void set_equipmentname(const char* value, size_t size);
  ::std::string* mutable_equipmentname();
  ::std::string* release_equipmentname();
  void set_allocated_equipmentname(::std::string* equipmentname);

  // string messageId = 2;
  void clear_messageid();
  static const int kMessageIdFieldNumber = 2;
  const ::std::string& messageid() const;
  void set_messageid(const ::std::string& value);
  #if LANG_CXX11
  void set_messageid(::std::string&& value);
  #endif
  void set_messageid(const char* value);
  void set_messageid(const char* value, size_t size);
  ::std::string* mutable_messageid();
  ::std::string* release_messageid();
  void set_allocated_messageid(::std::string* messageid);

  // uint64 timestamp = 3;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 3;
  ::google::protobuf::uint64 timestamp() const;
  void set_timestamp(::google::protobuf::uint64 value);

  // int32 eventType = 4;
  void clear_eventtype();
  static const int kEventTypeFieldNumber = 4;
  ::google::protobuf::int32 eventtype() const;
  void set_eventtype(::google::protobuf::int32 value);

  // int32 stateType = 5;
  void clear_statetype();
  static const int kStateTypeFieldNumber = 5;
  ::google::protobuf::int32 statetype() const;
  void set_statetype(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:PciRobotEvent)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr equipmentname_;
  ::google::protobuf::internal::ArenaStringPtr messageid_;
  ::google::protobuf::uint64 timestamp_;
  ::google::protobuf::int32 eventtype_;
  ::google::protobuf::int32 statetype_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_orige_5fmessage_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PciRobotEvent

// string equipmentName = 1;
inline void PciRobotEvent::clear_equipmentname() {
  equipmentname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PciRobotEvent::equipmentname() const {
  // @@protoc_insertion_point(field_get:PciRobotEvent.equipmentName)
  return equipmentname_.GetNoArena();
}
inline void PciRobotEvent::set_equipmentname(const ::std::string& value) {
  
  equipmentname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PciRobotEvent.equipmentName)
}
#if LANG_CXX11
inline void PciRobotEvent::set_equipmentname(::std::string&& value) {
  
  equipmentname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:PciRobotEvent.equipmentName)
}
#endif
inline void PciRobotEvent::set_equipmentname(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  equipmentname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PciRobotEvent.equipmentName)
}
inline void PciRobotEvent::set_equipmentname(const char* value, size_t size) {
  
  equipmentname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PciRobotEvent.equipmentName)
}
inline ::std::string* PciRobotEvent::mutable_equipmentname() {
  
  // @@protoc_insertion_point(field_mutable:PciRobotEvent.equipmentName)
  return equipmentname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PciRobotEvent::release_equipmentname() {
  // @@protoc_insertion_point(field_release:PciRobotEvent.equipmentName)
  
  return equipmentname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PciRobotEvent::set_allocated_equipmentname(::std::string* equipmentname) {
  if (equipmentname != NULL) {
    
  } else {
    
  }
  equipmentname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), equipmentname);
  // @@protoc_insertion_point(field_set_allocated:PciRobotEvent.equipmentName)
}

// string messageId = 2;
inline void PciRobotEvent::clear_messageid() {
  messageid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PciRobotEvent::messageid() const {
  // @@protoc_insertion_point(field_get:PciRobotEvent.messageId)
  return messageid_.GetNoArena();
}
inline void PciRobotEvent::set_messageid(const ::std::string& value) {
  
  messageid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PciRobotEvent.messageId)
}
#if LANG_CXX11
inline void PciRobotEvent::set_messageid(::std::string&& value) {
  
  messageid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:PciRobotEvent.messageId)
}
#endif
inline void PciRobotEvent::set_messageid(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  messageid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PciRobotEvent.messageId)
}
inline void PciRobotEvent::set_messageid(const char* value, size_t size) {
  
  messageid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PciRobotEvent.messageId)
}
inline ::std::string* PciRobotEvent::mutable_messageid() {
  
  // @@protoc_insertion_point(field_mutable:PciRobotEvent.messageId)
  return messageid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PciRobotEvent::release_messageid() {
  // @@protoc_insertion_point(field_release:PciRobotEvent.messageId)
  
  return messageid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PciRobotEvent::set_allocated_messageid(::std::string* messageid) {
  if (messageid != NULL) {
    
  } else {
    
  }
  messageid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), messageid);
  // @@protoc_insertion_point(field_set_allocated:PciRobotEvent.messageId)
}

// uint64 timestamp = 3;
inline void PciRobotEvent::clear_timestamp() {
  timestamp_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 PciRobotEvent::timestamp() const {
  // @@protoc_insertion_point(field_get:PciRobotEvent.timestamp)
  return timestamp_;
}
inline void PciRobotEvent::set_timestamp(::google::protobuf::uint64 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:PciRobotEvent.timestamp)
}

// int32 eventType = 4;
inline void PciRobotEvent::clear_eventtype() {
  eventtype_ = 0;
}
inline ::google::protobuf::int32 PciRobotEvent::eventtype() const {
  // @@protoc_insertion_point(field_get:PciRobotEvent.eventType)
  return eventtype_;
}
inline void PciRobotEvent::set_eventtype(::google::protobuf::int32 value) {
  
  eventtype_ = value;
  // @@protoc_insertion_point(field_set:PciRobotEvent.eventType)
}

// int32 stateType = 5;
inline void PciRobotEvent::clear_statetype() {
  statetype_ = 0;
}
inline ::google::protobuf::int32 PciRobotEvent::statetype() const {
  // @@protoc_insertion_point(field_get:PciRobotEvent.stateType)
  return statetype_;
}
inline void PciRobotEvent::set_statetype(::google::protobuf::int32 value) {
  
  statetype_ = value;
  // @@protoc_insertion_point(field_set:PciRobotEvent.stateType)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_orige_5fmessage_2eproto
