// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: orige_message.proto

#include "orige_message.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

class PciRobotEventDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PciRobotEvent>
      _instance;
} _PciRobotEvent_default_instance_;
namespace protobuf_orige_5fmessage_2eproto {
static void InitDefaultsPciRobotEvent() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_PciRobotEvent_default_instance_;
    new (ptr) ::PciRobotEvent();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::PciRobotEvent::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_PciRobotEvent =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsPciRobotEvent}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_PciRobotEvent.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PciRobotEvent, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PciRobotEvent, equipmentname_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PciRobotEvent, messageid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PciRobotEvent, timestamp_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PciRobotEvent, eventtype_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PciRobotEvent, statetype_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::PciRobotEvent)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_PciRobotEvent_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "orige_message.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\023orige_message.proto\"r\n\rPciRobotEvent\022\025"
      "\n\requipmentName\030\001 \001(\t\022\021\n\tmessageId\030\002 \001(\t"
      "\022\021\n\ttimestamp\030\003 \001(\004\022\021\n\teventType\030\004 \001(\005\022\021"
      "\n\tstateType\030\005 \001(\005b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 145);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "orige_message.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_orige_5fmessage_2eproto

// ===================================================================

void PciRobotEvent::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PciRobotEvent::kEquipmentNameFieldNumber;
const int PciRobotEvent::kMessageIdFieldNumber;
const int PciRobotEvent::kTimestampFieldNumber;
const int PciRobotEvent::kEventTypeFieldNumber;
const int PciRobotEvent::kStateTypeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PciRobotEvent::PciRobotEvent()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_orige_5fmessage_2eproto::scc_info_PciRobotEvent.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:PciRobotEvent)
}
PciRobotEvent::PciRobotEvent(const PciRobotEvent& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  equipmentname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.equipmentname().size() > 0) {
    equipmentname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.equipmentname_);
  }
  messageid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.messageid().size() > 0) {
    messageid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.messageid_);
  }
  ::memcpy(&timestamp_, &from.timestamp_,
    static_cast<size_t>(reinterpret_cast<char*>(&statetype_) -
    reinterpret_cast<char*>(&timestamp_)) + sizeof(statetype_));
  // @@protoc_insertion_point(copy_constructor:PciRobotEvent)
}

void PciRobotEvent::SharedCtor() {
  equipmentname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  messageid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&timestamp_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&statetype_) -
      reinterpret_cast<char*>(&timestamp_)) + sizeof(statetype_));
}

PciRobotEvent::~PciRobotEvent() {
  // @@protoc_insertion_point(destructor:PciRobotEvent)
  SharedDtor();
}

void PciRobotEvent::SharedDtor() {
  equipmentname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  messageid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void PciRobotEvent::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* PciRobotEvent::descriptor() {
  ::protobuf_orige_5fmessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_orige_5fmessage_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const PciRobotEvent& PciRobotEvent::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_orige_5fmessage_2eproto::scc_info_PciRobotEvent.base);
  return *internal_default_instance();
}


void PciRobotEvent::Clear() {
// @@protoc_insertion_point(message_clear_start:PciRobotEvent)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  equipmentname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  messageid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&timestamp_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&statetype_) -
      reinterpret_cast<char*>(&timestamp_)) + sizeof(statetype_));
  _internal_metadata_.Clear();
}

bool PciRobotEvent::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PciRobotEvent)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string equipmentName = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_equipmentname()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->equipmentname().data(), static_cast<int>(this->equipmentname().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "PciRobotEvent.equipmentName"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string messageId = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_messageid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->messageid().data(), static_cast<int>(this->messageid().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "PciRobotEvent.messageId"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 timestamp = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &timestamp_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 eventType = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &eventtype_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 stateType = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &statetype_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:PciRobotEvent)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PciRobotEvent)
  return false;
#undef DO_
}

void PciRobotEvent::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PciRobotEvent)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string equipmentName = 1;
  if (this->equipmentname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->equipmentname().data(), static_cast<int>(this->equipmentname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PciRobotEvent.equipmentName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->equipmentname(), output);
  }

  // string messageId = 2;
  if (this->messageid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->messageid().data(), static_cast<int>(this->messageid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PciRobotEvent.messageId");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->messageid(), output);
  }

  // uint64 timestamp = 3;
  if (this->timestamp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(3, this->timestamp(), output);
  }

  // int32 eventType = 4;
  if (this->eventtype() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->eventtype(), output);
  }

  // int32 stateType = 5;
  if (this->statetype() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->statetype(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:PciRobotEvent)
}

::google::protobuf::uint8* PciRobotEvent::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:PciRobotEvent)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string equipmentName = 1;
  if (this->equipmentname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->equipmentname().data(), static_cast<int>(this->equipmentname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PciRobotEvent.equipmentName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->equipmentname(), target);
  }

  // string messageId = 2;
  if (this->messageid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->messageid().data(), static_cast<int>(this->messageid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PciRobotEvent.messageId");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->messageid(), target);
  }

  // uint64 timestamp = 3;
  if (this->timestamp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(3, this->timestamp(), target);
  }

  // int32 eventType = 4;
  if (this->eventtype() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->eventtype(), target);
  }

  // int32 stateType = 5;
  if (this->statetype() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->statetype(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PciRobotEvent)
  return target;
}

size_t PciRobotEvent::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PciRobotEvent)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string equipmentName = 1;
  if (this->equipmentname().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->equipmentname());
  }

  // string messageId = 2;
  if (this->messageid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->messageid());
  }

  // uint64 timestamp = 3;
  if (this->timestamp() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->timestamp());
  }

  // int32 eventType = 4;
  if (this->eventtype() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->eventtype());
  }

  // int32 stateType = 5;
  if (this->statetype() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->statetype());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PciRobotEvent::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:PciRobotEvent)
  GOOGLE_DCHECK_NE(&from, this);
  const PciRobotEvent* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PciRobotEvent>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:PciRobotEvent)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:PciRobotEvent)
    MergeFrom(*source);
  }
}

void PciRobotEvent::MergeFrom(const PciRobotEvent& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:PciRobotEvent)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.equipmentname().size() > 0) {

    equipmentname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.equipmentname_);
  }
  if (from.messageid().size() > 0) {

    messageid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.messageid_);
  }
  if (from.timestamp() != 0) {
    set_timestamp(from.timestamp());
  }
  if (from.eventtype() != 0) {
    set_eventtype(from.eventtype());
  }
  if (from.statetype() != 0) {
    set_statetype(from.statetype());
  }
}

void PciRobotEvent::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:PciRobotEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PciRobotEvent::CopyFrom(const PciRobotEvent& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PciRobotEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PciRobotEvent::IsInitialized() const {
  return true;
}

void PciRobotEvent::Swap(PciRobotEvent* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PciRobotEvent::InternalSwap(PciRobotEvent* other) {
  using std::swap;
  equipmentname_.Swap(&other->equipmentname_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  messageid_.Swap(&other->messageid_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(timestamp_, other->timestamp_);
  swap(eventtype_, other->eventtype_);
  swap(statetype_, other->statetype_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata PciRobotEvent::GetMetadata() const {
  protobuf_orige_5fmessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_orige_5fmessage_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::PciRobotEvent* Arena::CreateMaybeMessage< ::PciRobotEvent >(Arena* arena) {
  return Arena::CreateInternal< ::PciRobotEvent >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
