// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_base/robot_base_msgs.proto

#ifndef PROTOBUF_INCLUDED_robot_5fbase_2frobot_5fbase_5fmsgs_2eproto
#define PROTOBUF_INCLUDED_robot_5fbase_2frobot_5fbase_5fmsgs_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_robot_5fbase_2frobot_5fbase_5fmsgs_2eproto 

namespace protobuf_robot_5fbase_2frobot_5fbase_5fmsgs_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[13];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
}  // namespace protobuf_robot_5fbase_2frobot_5fbase_5fmsgs_2eproto
namespace robot_base_msgs {
class ArmTarget;
class ArmTargetDefaultTypeInternal;
extern ArmTargetDefaultTypeInternal _ArmTarget_default_instance_;
class BaseState;
class BaseStateDefaultTypeInternal;
extern BaseStateDefaultTypeInternal _BaseState_default_instance_;
class BmsInfo;
class BmsInfoDefaultTypeInternal;
extern BmsInfoDefaultTypeInternal _BmsInfo_default_instance_;
class CtrlCmd;
class CtrlCmdDefaultTypeInternal;
extern CtrlCmdDefaultTypeInternal _CtrlCmd_default_instance_;
class HeartBeat;
class HeartBeatDefaultTypeInternal;
extern HeartBeatDefaultTypeInternal _HeartBeat_default_instance_;
class ImuData;
class ImuDataDefaultTypeInternal;
extern ImuDataDefaultTypeInternal _ImuData_default_instance_;
class MapInfo;
class MapInfoDefaultTypeInternal;
extern MapInfoDefaultTypeInternal _MapInfo_default_instance_;
class MotionData;
class MotionDataDefaultTypeInternal;
extern MotionDataDefaultTypeInternal _MotionData_default_instance_;
class MotorState;
class MotorStateDefaultTypeInternal;
extern MotorStateDefaultTypeInternal _MotorState_default_instance_;
class NavState;
class NavStateDefaultTypeInternal;
extern NavStateDefaultTypeInternal _NavState_default_instance_;
class OdomData;
class OdomDataDefaultTypeInternal;
extern OdomDataDefaultTypeInternal _OdomData_default_instance_;
class RobotBaseOp;
class RobotBaseOpDefaultTypeInternal;
extern RobotBaseOpDefaultTypeInternal _RobotBaseOp_default_instance_;
class RobotNavLocInfo;
class RobotNavLocInfoDefaultTypeInternal;
extern RobotNavLocInfoDefaultTypeInternal _RobotNavLocInfo_default_instance_;
}  // namespace robot_base_msgs
namespace google {
namespace protobuf {
template<> ::robot_base_msgs::ArmTarget* Arena::CreateMaybeMessage<::robot_base_msgs::ArmTarget>(Arena*);
template<> ::robot_base_msgs::BaseState* Arena::CreateMaybeMessage<::robot_base_msgs::BaseState>(Arena*);
template<> ::robot_base_msgs::BmsInfo* Arena::CreateMaybeMessage<::robot_base_msgs::BmsInfo>(Arena*);
template<> ::robot_base_msgs::CtrlCmd* Arena::CreateMaybeMessage<::robot_base_msgs::CtrlCmd>(Arena*);
template<> ::robot_base_msgs::HeartBeat* Arena::CreateMaybeMessage<::robot_base_msgs::HeartBeat>(Arena*);
template<> ::robot_base_msgs::ImuData* Arena::CreateMaybeMessage<::robot_base_msgs::ImuData>(Arena*);
template<> ::robot_base_msgs::MapInfo* Arena::CreateMaybeMessage<::robot_base_msgs::MapInfo>(Arena*);
template<> ::robot_base_msgs::MotionData* Arena::CreateMaybeMessage<::robot_base_msgs::MotionData>(Arena*);
template<> ::robot_base_msgs::MotorState* Arena::CreateMaybeMessage<::robot_base_msgs::MotorState>(Arena*);
template<> ::robot_base_msgs::NavState* Arena::CreateMaybeMessage<::robot_base_msgs::NavState>(Arena*);
template<> ::robot_base_msgs::OdomData* Arena::CreateMaybeMessage<::robot_base_msgs::OdomData>(Arena*);
template<> ::robot_base_msgs::RobotBaseOp* Arena::CreateMaybeMessage<::robot_base_msgs::RobotBaseOp>(Arena*);
template<> ::robot_base_msgs::RobotNavLocInfo* Arena::CreateMaybeMessage<::robot_base_msgs::RobotNavLocInfo>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace robot_base_msgs {

// ===================================================================

class BaseState : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:robot_base_msgs.BaseState) */ {
 public:
  BaseState();
  virtual ~BaseState();

  BaseState(const BaseState& from);

  inline BaseState& operator=(const BaseState& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BaseState(BaseState&& from) noexcept
    : BaseState() {
    *this = ::std::move(from);
  }

  inline BaseState& operator=(BaseState&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const BaseState& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BaseState* internal_default_instance() {
    return reinterpret_cast<const BaseState*>(
               &_BaseState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(BaseState* other);
  friend void swap(BaseState& a, BaseState& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BaseState* New() const final {
    return CreateMaybeMessage<BaseState>(NULL);
  }

  BaseState* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<BaseState>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const BaseState& from);
  void MergeFrom(const BaseState& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(BaseState* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double timestamp = 1;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  double timestamp() const;
  void set_timestamp(double value);

  // uint64 base_state = 2;
  void clear_base_state();
  static const int kBaseStateFieldNumber = 2;
  ::google::protobuf::uint64 base_state() const;
  void set_base_state(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:robot_base_msgs.BaseState)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  double timestamp_;
  ::google::protobuf::uint64 base_state_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_robot_5fbase_2frobot_5fbase_5fmsgs_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class MotorState : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:robot_base_msgs.MotorState) */ {
 public:
  MotorState();
  virtual ~MotorState();

  MotorState(const MotorState& from);

  inline MotorState& operator=(const MotorState& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MotorState(MotorState&& from) noexcept
    : MotorState() {
    *this = ::std::move(from);
  }

  inline MotorState& operator=(MotorState&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const MotorState& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MotorState* internal_default_instance() {
    return reinterpret_cast<const MotorState*>(
               &_MotorState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(MotorState* other);
  friend void swap(MotorState& a, MotorState& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MotorState* New() const final {
    return CreateMaybeMessage<MotorState>(NULL);
  }

  MotorState* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<MotorState>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const MotorState& from);
  void MergeFrom(const MotorState& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MotorState* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double timestamp = 1;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  double timestamp() const;
  void set_timestamp(double value);

  // uint64 motor_state = 2;
  void clear_motor_state();
  static const int kMotorStateFieldNumber = 2;
  ::google::protobuf::uint64 motor_state() const;
  void set_motor_state(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:robot_base_msgs.MotorState)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  double timestamp_;
  ::google::protobuf::uint64 motor_state_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_robot_5fbase_2frobot_5fbase_5fmsgs_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class OdomData : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:robot_base_msgs.OdomData) */ {
 public:
  OdomData();
  virtual ~OdomData();

  OdomData(const OdomData& from);

  inline OdomData& operator=(const OdomData& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  OdomData(OdomData&& from) noexcept
    : OdomData() {
    *this = ::std::move(from);
  }

  inline OdomData& operator=(OdomData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const OdomData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const OdomData* internal_default_instance() {
    return reinterpret_cast<const OdomData*>(
               &_OdomData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(OdomData* other);
  friend void swap(OdomData& a, OdomData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline OdomData* New() const final {
    return CreateMaybeMessage<OdomData>(NULL);
  }

  OdomData* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<OdomData>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const OdomData& from);
  void MergeFrom(const OdomData& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(OdomData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double timestamp = 1;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  double timestamp() const;
  void set_timestamp(double value);

  // uint64 odom_data = 2;
  void clear_odom_data();
  static const int kOdomDataFieldNumber = 2;
  ::google::protobuf::uint64 odom_data() const;
  void set_odom_data(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:robot_base_msgs.OdomData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  double timestamp_;
  ::google::protobuf::uint64 odom_data_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_robot_5fbase_2frobot_5fbase_5fmsgs_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ImuData : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:robot_base_msgs.ImuData) */ {
 public:
  ImuData();
  virtual ~ImuData();

  ImuData(const ImuData& from);

  inline ImuData& operator=(const ImuData& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ImuData(ImuData&& from) noexcept
    : ImuData() {
    *this = ::std::move(from);
  }

  inline ImuData& operator=(ImuData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ImuData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ImuData* internal_default_instance() {
    return reinterpret_cast<const ImuData*>(
               &_ImuData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(ImuData* other);
  friend void swap(ImuData& a, ImuData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ImuData* New() const final {
    return CreateMaybeMessage<ImuData>(NULL);
  }

  ImuData* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ImuData>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const ImuData& from);
  void MergeFrom(const ImuData& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ImuData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double timestamp = 1;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  double timestamp() const;
  void set_timestamp(double value);

  // uint64 acc_data = 2;
  void clear_acc_data();
  static const int kAccDataFieldNumber = 2;
  ::google::protobuf::uint64 acc_data() const;
  void set_acc_data(::google::protobuf::uint64 value);

  // uint64 gyro_data = 3;
  void clear_gyro_data();
  static const int kGyroDataFieldNumber = 3;
  ::google::protobuf::uint64 gyro_data() const;
  void set_gyro_data(::google::protobuf::uint64 value);

  // uint64 orientation_data = 4;
  void clear_orientation_data();
  static const int kOrientationDataFieldNumber = 4;
  ::google::protobuf::uint64 orientation_data() const;
  void set_orientation_data(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:robot_base_msgs.ImuData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  double timestamp_;
  ::google::protobuf::uint64 acc_data_;
  ::google::protobuf::uint64 gyro_data_;
  ::google::protobuf::uint64 orientation_data_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_robot_5fbase_2frobot_5fbase_5fmsgs_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class BmsInfo : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:robot_base_msgs.BmsInfo) */ {
 public:
  BmsInfo();
  virtual ~BmsInfo();

  BmsInfo(const BmsInfo& from);

  inline BmsInfo& operator=(const BmsInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BmsInfo(BmsInfo&& from) noexcept
    : BmsInfo() {
    *this = ::std::move(from);
  }

  inline BmsInfo& operator=(BmsInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const BmsInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BmsInfo* internal_default_instance() {
    return reinterpret_cast<const BmsInfo*>(
               &_BmsInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(BmsInfo* other);
  friend void swap(BmsInfo& a, BmsInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BmsInfo* New() const final {
    return CreateMaybeMessage<BmsInfo>(NULL);
  }

  BmsInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<BmsInfo>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const BmsInfo& from);
  void MergeFrom(const BmsInfo& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(BmsInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double timestmap = 1;
  void clear_timestmap();
  static const int kTimestmapFieldNumber = 1;
  double timestmap() const;
  void set_timestmap(double value);

  // uint64 bms_info = 2;
  void clear_bms_info();
  static const int kBmsInfoFieldNumber = 2;
  ::google::protobuf::uint64 bms_info() const;
  void set_bms_info(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:robot_base_msgs.BmsInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  double timestmap_;
  ::google::protobuf::uint64 bms_info_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_robot_5fbase_2frobot_5fbase_5fmsgs_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class NavState : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:robot_base_msgs.NavState) */ {
 public:
  NavState();
  virtual ~NavState();

  NavState(const NavState& from);

  inline NavState& operator=(const NavState& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  NavState(NavState&& from) noexcept
    : NavState() {
    *this = ::std::move(from);
  }

  inline NavState& operator=(NavState&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const NavState& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NavState* internal_default_instance() {
    return reinterpret_cast<const NavState*>(
               &_NavState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(NavState* other);
  friend void swap(NavState& a, NavState& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline NavState* New() const final {
    return CreateMaybeMessage<NavState>(NULL);
  }

  NavState* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<NavState>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const NavState& from);
  void MergeFrom(const NavState& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(NavState* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double timestmap = 1;
  void clear_timestmap();
  static const int kTimestmapFieldNumber = 1;
  double timestmap() const;
  void set_timestmap(double value);

  // uint64 nav_state = 2;
  void clear_nav_state();
  static const int kNavStateFieldNumber = 2;
  ::google::protobuf::uint64 nav_state() const;
  void set_nav_state(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:robot_base_msgs.NavState)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  double timestmap_;
  ::google::protobuf::uint64 nav_state_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_robot_5fbase_2frobot_5fbase_5fmsgs_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class CtrlCmd : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:robot_base_msgs.CtrlCmd) */ {
 public:
  CtrlCmd();
  virtual ~CtrlCmd();

  CtrlCmd(const CtrlCmd& from);

  inline CtrlCmd& operator=(const CtrlCmd& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CtrlCmd(CtrlCmd&& from) noexcept
    : CtrlCmd() {
    *this = ::std::move(from);
  }

  inline CtrlCmd& operator=(CtrlCmd&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const CtrlCmd& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CtrlCmd* internal_default_instance() {
    return reinterpret_cast<const CtrlCmd*>(
               &_CtrlCmd_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(CtrlCmd* other);
  friend void swap(CtrlCmd& a, CtrlCmd& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CtrlCmd* New() const final {
    return CreateMaybeMessage<CtrlCmd>(NULL);
  }

  CtrlCmd* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CtrlCmd>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const CtrlCmd& from);
  void MergeFrom(const CtrlCmd& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CtrlCmd* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double timestamp = 1;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  double timestamp() const;
  void set_timestamp(double value);

  // uint64 ctrl_cmd = 2;
  void clear_ctrl_cmd();
  static const int kCtrlCmdFieldNumber = 2;
  ::google::protobuf::uint64 ctrl_cmd() const;
  void set_ctrl_cmd(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:robot_base_msgs.CtrlCmd)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  double timestamp_;
  ::google::protobuf::uint64 ctrl_cmd_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_robot_5fbase_2frobot_5fbase_5fmsgs_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class MotionData : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:robot_base_msgs.MotionData) */ {
 public:
  MotionData();
  virtual ~MotionData();

  MotionData(const MotionData& from);

  inline MotionData& operator=(const MotionData& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MotionData(MotionData&& from) noexcept
    : MotionData() {
    *this = ::std::move(from);
  }

  inline MotionData& operator=(MotionData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const MotionData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MotionData* internal_default_instance() {
    return reinterpret_cast<const MotionData*>(
               &_MotionData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  void Swap(MotionData* other);
  friend void swap(MotionData& a, MotionData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MotionData* New() const final {
    return CreateMaybeMessage<MotionData>(NULL);
  }

  MotionData* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<MotionData>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const MotionData& from);
  void MergeFrom(const MotionData& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MotionData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double timestamp = 1;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  double timestamp() const;
  void set_timestamp(double value);

  // uint64 motion_data = 2;
  void clear_motion_data();
  static const int kMotionDataFieldNumber = 2;
  ::google::protobuf::uint64 motion_data() const;
  void set_motion_data(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:robot_base_msgs.MotionData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  double timestamp_;
  ::google::protobuf::uint64 motion_data_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_robot_5fbase_2frobot_5fbase_5fmsgs_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class HeartBeat : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:robot_base_msgs.HeartBeat) */ {
 public:
  HeartBeat();
  virtual ~HeartBeat();

  HeartBeat(const HeartBeat& from);

  inline HeartBeat& operator=(const HeartBeat& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  HeartBeat(HeartBeat&& from) noexcept
    : HeartBeat() {
    *this = ::std::move(from);
  }

  inline HeartBeat& operator=(HeartBeat&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const HeartBeat& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const HeartBeat* internal_default_instance() {
    return reinterpret_cast<const HeartBeat*>(
               &_HeartBeat_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  void Swap(HeartBeat* other);
  friend void swap(HeartBeat& a, HeartBeat& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline HeartBeat* New() const final {
    return CreateMaybeMessage<HeartBeat>(NULL);
  }

  HeartBeat* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<HeartBeat>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const HeartBeat& from);
  void MergeFrom(const HeartBeat& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(HeartBeat* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double timestamp = 1;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  double timestamp() const;
  void set_timestamp(double value);

  // uint64 reserve = 2;
  void clear_reserve();
  static const int kReserveFieldNumber = 2;
  ::google::protobuf::uint64 reserve() const;
  void set_reserve(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:robot_base_msgs.HeartBeat)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  double timestamp_;
  ::google::protobuf::uint64 reserve_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_robot_5fbase_2frobot_5fbase_5fmsgs_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class MapInfo : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:robot_base_msgs.MapInfo) */ {
 public:
  MapInfo();
  virtual ~MapInfo();

  MapInfo(const MapInfo& from);

  inline MapInfo& operator=(const MapInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MapInfo(MapInfo&& from) noexcept
    : MapInfo() {
    *this = ::std::move(from);
  }

  inline MapInfo& operator=(MapInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const MapInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MapInfo* internal_default_instance() {
    return reinterpret_cast<const MapInfo*>(
               &_MapInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    9;

  void Swap(MapInfo* other);
  friend void swap(MapInfo& a, MapInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MapInfo* New() const final {
    return CreateMaybeMessage<MapInfo>(NULL);
  }

  MapInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<MapInfo>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const MapInfo& from);
  void MergeFrom(const MapInfo& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MapInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double timestamp = 1;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  double timestamp() const;
  void set_timestamp(double value);

  // uint64 reserver_1 = 2;
  void clear_reserver_1();
  static const int kReserver1FieldNumber = 2;
  ::google::protobuf::uint64 reserver_1() const;
  void set_reserver_1(::google::protobuf::uint64 value);

  // uint64 reserver_2 = 3;
  void clear_reserver_2();
  static const int kReserver2FieldNumber = 3;
  ::google::protobuf::uint64 reserver_2() const;
  void set_reserver_2(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:robot_base_msgs.MapInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  double timestamp_;
  ::google::protobuf::uint64 reserver_1_;
  ::google::protobuf::uint64 reserver_2_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_robot_5fbase_2frobot_5fbase_5fmsgs_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ArmTarget : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:robot_base_msgs.ArmTarget) */ {
 public:
  ArmTarget();
  virtual ~ArmTarget();

  ArmTarget(const ArmTarget& from);

  inline ArmTarget& operator=(const ArmTarget& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ArmTarget(ArmTarget&& from) noexcept
    : ArmTarget() {
    *this = ::std::move(from);
  }

  inline ArmTarget& operator=(ArmTarget&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ArmTarget& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ArmTarget* internal_default_instance() {
    return reinterpret_cast<const ArmTarget*>(
               &_ArmTarget_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    10;

  void Swap(ArmTarget* other);
  friend void swap(ArmTarget& a, ArmTarget& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ArmTarget* New() const final {
    return CreateMaybeMessage<ArmTarget>(NULL);
  }

  ArmTarget* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ArmTarget>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const ArmTarget& from);
  void MergeFrom(const ArmTarget& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ArmTarget* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double timestamp = 1;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  double timestamp() const;
  void set_timestamp(double value);

  // uint64 position_data = 2;
  void clear_position_data();
  static const int kPositionDataFieldNumber = 2;
  ::google::protobuf::uint64 position_data() const;
  void set_position_data(::google::protobuf::uint64 value);

  // uint64 orientation_data = 3;
  void clear_orientation_data();
  static const int kOrientationDataFieldNumber = 3;
  ::google::protobuf::uint64 orientation_data() const;
  void set_orientation_data(::google::protobuf::uint64 value);

  // uint64 params_data = 4;
  void clear_params_data();
  static const int kParamsDataFieldNumber = 4;
  ::google::protobuf::uint64 params_data() const;
  void set_params_data(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:robot_base_msgs.ArmTarget)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  double timestamp_;
  ::google::protobuf::uint64 position_data_;
  ::google::protobuf::uint64 orientation_data_;
  ::google::protobuf::uint64 params_data_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_robot_5fbase_2frobot_5fbase_5fmsgs_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RobotBaseOp : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:robot_base_msgs.RobotBaseOp) */ {
 public:
  RobotBaseOp();
  virtual ~RobotBaseOp();

  RobotBaseOp(const RobotBaseOp& from);

  inline RobotBaseOp& operator=(const RobotBaseOp& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RobotBaseOp(RobotBaseOp&& from) noexcept
    : RobotBaseOp() {
    *this = ::std::move(from);
  }

  inline RobotBaseOp& operator=(RobotBaseOp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const RobotBaseOp& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RobotBaseOp* internal_default_instance() {
    return reinterpret_cast<const RobotBaseOp*>(
               &_RobotBaseOp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    11;

  void Swap(RobotBaseOp* other);
  friend void swap(RobotBaseOp& a, RobotBaseOp& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RobotBaseOp* New() const final {
    return CreateMaybeMessage<RobotBaseOp>(NULL);
  }

  RobotBaseOp* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RobotBaseOp>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const RobotBaseOp& from);
  void MergeFrom(const RobotBaseOp& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RobotBaseOp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double timestamp = 1;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  double timestamp() const;
  void set_timestamp(double value);

  // uint64 op_data = 2;
  void clear_op_data();
  static const int kOpDataFieldNumber = 2;
  ::google::protobuf::uint64 op_data() const;
  void set_op_data(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:robot_base_msgs.RobotBaseOp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  double timestamp_;
  ::google::protobuf::uint64 op_data_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_robot_5fbase_2frobot_5fbase_5fmsgs_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RobotNavLocInfo : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:robot_base_msgs.RobotNavLocInfo) */ {
 public:
  RobotNavLocInfo();
  virtual ~RobotNavLocInfo();

  RobotNavLocInfo(const RobotNavLocInfo& from);

  inline RobotNavLocInfo& operator=(const RobotNavLocInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RobotNavLocInfo(RobotNavLocInfo&& from) noexcept
    : RobotNavLocInfo() {
    *this = ::std::move(from);
  }

  inline RobotNavLocInfo& operator=(RobotNavLocInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const RobotNavLocInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RobotNavLocInfo* internal_default_instance() {
    return reinterpret_cast<const RobotNavLocInfo*>(
               &_RobotNavLocInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    12;

  void Swap(RobotNavLocInfo* other);
  friend void swap(RobotNavLocInfo& a, RobotNavLocInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RobotNavLocInfo* New() const final {
    return CreateMaybeMessage<RobotNavLocInfo>(NULL);
  }

  RobotNavLocInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RobotNavLocInfo>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const RobotNavLocInfo& from);
  void MergeFrom(const RobotNavLocInfo& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RobotNavLocInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double timestamp = 1;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  double timestamp() const;
  void set_timestamp(double value);

  // sint32 nav_loc_state = 2;
  void clear_nav_loc_state();
  static const int kNavLocStateFieldNumber = 2;
  ::google::protobuf::int32 nav_loc_state() const;
  void set_nav_loc_state(::google::protobuf::int32 value);

  // int32 pos_x = 3;
  void clear_pos_x();
  static const int kPosXFieldNumber = 3;
  ::google::protobuf::int32 pos_x() const;
  void set_pos_x(::google::protobuf::int32 value);

  // int32 pos_y = 4;
  void clear_pos_y();
  static const int kPosYFieldNumber = 4;
  ::google::protobuf::int32 pos_y() const;
  void set_pos_y(::google::protobuf::int32 value);

  // int32 pos_z = 5;
  void clear_pos_z();
  static const int kPosZFieldNumber = 5;
  ::google::protobuf::int32 pos_z() const;
  void set_pos_z(::google::protobuf::int32 value);

  // int32 quat_x = 6;
  void clear_quat_x();
  static const int kQuatXFieldNumber = 6;
  ::google::protobuf::int32 quat_x() const;
  void set_quat_x(::google::protobuf::int32 value);

  // int32 quat_y = 7;
  void clear_quat_y();
  static const int kQuatYFieldNumber = 7;
  ::google::protobuf::int32 quat_y() const;
  void set_quat_y(::google::protobuf::int32 value);

  // int32 quat_z = 8;
  void clear_quat_z();
  static const int kQuatZFieldNumber = 8;
  ::google::protobuf::int32 quat_z() const;
  void set_quat_z(::google::protobuf::int32 value);

  // int32 quat_w = 9;
  void clear_quat_w();
  static const int kQuatWFieldNumber = 9;
  ::google::protobuf::int32 quat_w() const;
  void set_quat_w(::google::protobuf::int32 value);

  // int32 vel_x = 10;
  void clear_vel_x();
  static const int kVelXFieldNumber = 10;
  ::google::protobuf::int32 vel_x() const;
  void set_vel_x(::google::protobuf::int32 value);

  // int32 vel_y = 11;
  void clear_vel_y();
  static const int kVelYFieldNumber = 11;
  ::google::protobuf::int32 vel_y() const;
  void set_vel_y(::google::protobuf::int32 value);

  // int32 vel_z = 12;
  void clear_vel_z();
  static const int kVelZFieldNumber = 12;
  ::google::protobuf::int32 vel_z() const;
  void set_vel_z(::google::protobuf::int32 value);

  // int32 angular_x = 13;
  void clear_angular_x();
  static const int kAngularXFieldNumber = 13;
  ::google::protobuf::int32 angular_x() const;
  void set_angular_x(::google::protobuf::int32 value);

  // int32 angular_y = 14;
  void clear_angular_y();
  static const int kAngularYFieldNumber = 14;
  ::google::protobuf::int32 angular_y() const;
  void set_angular_y(::google::protobuf::int32 value);

  // int32 angular_z = 15;
  void clear_angular_z();
  static const int kAngularZFieldNumber = 15;
  ::google::protobuf::int32 angular_z() const;
  void set_angular_z(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:robot_base_msgs.RobotNavLocInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  double timestamp_;
  ::google::protobuf::int32 nav_loc_state_;
  ::google::protobuf::int32 pos_x_;
  ::google::protobuf::int32 pos_y_;
  ::google::protobuf::int32 pos_z_;
  ::google::protobuf::int32 quat_x_;
  ::google::protobuf::int32 quat_y_;
  ::google::protobuf::int32 quat_z_;
  ::google::protobuf::int32 quat_w_;
  ::google::protobuf::int32 vel_x_;
  ::google::protobuf::int32 vel_y_;
  ::google::protobuf::int32 vel_z_;
  ::google::protobuf::int32 angular_x_;
  ::google::protobuf::int32 angular_y_;
  ::google::protobuf::int32 angular_z_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_robot_5fbase_2frobot_5fbase_5fmsgs_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BaseState

// double timestamp = 1;
inline void BaseState::clear_timestamp() {
  timestamp_ = 0;
}
inline double BaseState::timestamp() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.BaseState.timestamp)
  return timestamp_;
}
inline void BaseState::set_timestamp(double value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.BaseState.timestamp)
}

// uint64 base_state = 2;
inline void BaseState::clear_base_state() {
  base_state_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 BaseState::base_state() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.BaseState.base_state)
  return base_state_;
}
inline void BaseState::set_base_state(::google::protobuf::uint64 value) {
  
  base_state_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.BaseState.base_state)
}

// -------------------------------------------------------------------

// MotorState

// double timestamp = 1;
inline void MotorState::clear_timestamp() {
  timestamp_ = 0;
}
inline double MotorState::timestamp() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.MotorState.timestamp)
  return timestamp_;
}
inline void MotorState::set_timestamp(double value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.MotorState.timestamp)
}

// uint64 motor_state = 2;
inline void MotorState::clear_motor_state() {
  motor_state_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 MotorState::motor_state() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.MotorState.motor_state)
  return motor_state_;
}
inline void MotorState::set_motor_state(::google::protobuf::uint64 value) {
  
  motor_state_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.MotorState.motor_state)
}

// -------------------------------------------------------------------

// OdomData

// double timestamp = 1;
inline void OdomData::clear_timestamp() {
  timestamp_ = 0;
}
inline double OdomData::timestamp() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.OdomData.timestamp)
  return timestamp_;
}
inline void OdomData::set_timestamp(double value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.OdomData.timestamp)
}

// uint64 odom_data = 2;
inline void OdomData::clear_odom_data() {
  odom_data_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 OdomData::odom_data() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.OdomData.odom_data)
  return odom_data_;
}
inline void OdomData::set_odom_data(::google::protobuf::uint64 value) {
  
  odom_data_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.OdomData.odom_data)
}

// -------------------------------------------------------------------

// ImuData

// double timestamp = 1;
inline void ImuData::clear_timestamp() {
  timestamp_ = 0;
}
inline double ImuData::timestamp() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.ImuData.timestamp)
  return timestamp_;
}
inline void ImuData::set_timestamp(double value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.ImuData.timestamp)
}

// uint64 acc_data = 2;
inline void ImuData::clear_acc_data() {
  acc_data_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 ImuData::acc_data() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.ImuData.acc_data)
  return acc_data_;
}
inline void ImuData::set_acc_data(::google::protobuf::uint64 value) {
  
  acc_data_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.ImuData.acc_data)
}

// uint64 gyro_data = 3;
inline void ImuData::clear_gyro_data() {
  gyro_data_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 ImuData::gyro_data() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.ImuData.gyro_data)
  return gyro_data_;
}
inline void ImuData::set_gyro_data(::google::protobuf::uint64 value) {
  
  gyro_data_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.ImuData.gyro_data)
}

// uint64 orientation_data = 4;
inline void ImuData::clear_orientation_data() {
  orientation_data_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 ImuData::orientation_data() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.ImuData.orientation_data)
  return orientation_data_;
}
inline void ImuData::set_orientation_data(::google::protobuf::uint64 value) {
  
  orientation_data_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.ImuData.orientation_data)
}

// -------------------------------------------------------------------

// BmsInfo

// double timestmap = 1;
inline void BmsInfo::clear_timestmap() {
  timestmap_ = 0;
}
inline double BmsInfo::timestmap() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.BmsInfo.timestmap)
  return timestmap_;
}
inline void BmsInfo::set_timestmap(double value) {
  
  timestmap_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.BmsInfo.timestmap)
}

// uint64 bms_info = 2;
inline void BmsInfo::clear_bms_info() {
  bms_info_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 BmsInfo::bms_info() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.BmsInfo.bms_info)
  return bms_info_;
}
inline void BmsInfo::set_bms_info(::google::protobuf::uint64 value) {
  
  bms_info_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.BmsInfo.bms_info)
}

// -------------------------------------------------------------------

// NavState

// double timestmap = 1;
inline void NavState::clear_timestmap() {
  timestmap_ = 0;
}
inline double NavState::timestmap() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.NavState.timestmap)
  return timestmap_;
}
inline void NavState::set_timestmap(double value) {
  
  timestmap_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.NavState.timestmap)
}

// uint64 nav_state = 2;
inline void NavState::clear_nav_state() {
  nav_state_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 NavState::nav_state() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.NavState.nav_state)
  return nav_state_;
}
inline void NavState::set_nav_state(::google::protobuf::uint64 value) {
  
  nav_state_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.NavState.nav_state)
}

// -------------------------------------------------------------------

// CtrlCmd

// double timestamp = 1;
inline void CtrlCmd::clear_timestamp() {
  timestamp_ = 0;
}
inline double CtrlCmd::timestamp() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.CtrlCmd.timestamp)
  return timestamp_;
}
inline void CtrlCmd::set_timestamp(double value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.CtrlCmd.timestamp)
}

// uint64 ctrl_cmd = 2;
inline void CtrlCmd::clear_ctrl_cmd() {
  ctrl_cmd_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 CtrlCmd::ctrl_cmd() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.CtrlCmd.ctrl_cmd)
  return ctrl_cmd_;
}
inline void CtrlCmd::set_ctrl_cmd(::google::protobuf::uint64 value) {
  
  ctrl_cmd_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.CtrlCmd.ctrl_cmd)
}

// -------------------------------------------------------------------

// MotionData

// double timestamp = 1;
inline void MotionData::clear_timestamp() {
  timestamp_ = 0;
}
inline double MotionData::timestamp() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.MotionData.timestamp)
  return timestamp_;
}
inline void MotionData::set_timestamp(double value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.MotionData.timestamp)
}

// uint64 motion_data = 2;
inline void MotionData::clear_motion_data() {
  motion_data_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 MotionData::motion_data() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.MotionData.motion_data)
  return motion_data_;
}
inline void MotionData::set_motion_data(::google::protobuf::uint64 value) {
  
  motion_data_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.MotionData.motion_data)
}

// -------------------------------------------------------------------

// HeartBeat

// double timestamp = 1;
inline void HeartBeat::clear_timestamp() {
  timestamp_ = 0;
}
inline double HeartBeat::timestamp() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.HeartBeat.timestamp)
  return timestamp_;
}
inline void HeartBeat::set_timestamp(double value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.HeartBeat.timestamp)
}

// uint64 reserve = 2;
inline void HeartBeat::clear_reserve() {
  reserve_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 HeartBeat::reserve() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.HeartBeat.reserve)
  return reserve_;
}
inline void HeartBeat::set_reserve(::google::protobuf::uint64 value) {
  
  reserve_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.HeartBeat.reserve)
}

// -------------------------------------------------------------------

// MapInfo

// double timestamp = 1;
inline void MapInfo::clear_timestamp() {
  timestamp_ = 0;
}
inline double MapInfo::timestamp() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.MapInfo.timestamp)
  return timestamp_;
}
inline void MapInfo::set_timestamp(double value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.MapInfo.timestamp)
}

// uint64 reserver_1 = 2;
inline void MapInfo::clear_reserver_1() {
  reserver_1_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 MapInfo::reserver_1() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.MapInfo.reserver_1)
  return reserver_1_;
}
inline void MapInfo::set_reserver_1(::google::protobuf::uint64 value) {
  
  reserver_1_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.MapInfo.reserver_1)
}

// uint64 reserver_2 = 3;
inline void MapInfo::clear_reserver_2() {
  reserver_2_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 MapInfo::reserver_2() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.MapInfo.reserver_2)
  return reserver_2_;
}
inline void MapInfo::set_reserver_2(::google::protobuf::uint64 value) {
  
  reserver_2_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.MapInfo.reserver_2)
}

// -------------------------------------------------------------------

// ArmTarget

// double timestamp = 1;
inline void ArmTarget::clear_timestamp() {
  timestamp_ = 0;
}
inline double ArmTarget::timestamp() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.ArmTarget.timestamp)
  return timestamp_;
}
inline void ArmTarget::set_timestamp(double value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.ArmTarget.timestamp)
}

// uint64 position_data = 2;
inline void ArmTarget::clear_position_data() {
  position_data_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 ArmTarget::position_data() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.ArmTarget.position_data)
  return position_data_;
}
inline void ArmTarget::set_position_data(::google::protobuf::uint64 value) {
  
  position_data_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.ArmTarget.position_data)
}

// uint64 orientation_data = 3;
inline void ArmTarget::clear_orientation_data() {
  orientation_data_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 ArmTarget::orientation_data() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.ArmTarget.orientation_data)
  return orientation_data_;
}
inline void ArmTarget::set_orientation_data(::google::protobuf::uint64 value) {
  
  orientation_data_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.ArmTarget.orientation_data)
}

// uint64 params_data = 4;
inline void ArmTarget::clear_params_data() {
  params_data_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 ArmTarget::params_data() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.ArmTarget.params_data)
  return params_data_;
}
inline void ArmTarget::set_params_data(::google::protobuf::uint64 value) {
  
  params_data_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.ArmTarget.params_data)
}

// -------------------------------------------------------------------

// RobotBaseOp

// double timestamp = 1;
inline void RobotBaseOp::clear_timestamp() {
  timestamp_ = 0;
}
inline double RobotBaseOp::timestamp() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.RobotBaseOp.timestamp)
  return timestamp_;
}
inline void RobotBaseOp::set_timestamp(double value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.RobotBaseOp.timestamp)
}

// uint64 op_data = 2;
inline void RobotBaseOp::clear_op_data() {
  op_data_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 RobotBaseOp::op_data() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.RobotBaseOp.op_data)
  return op_data_;
}
inline void RobotBaseOp::set_op_data(::google::protobuf::uint64 value) {
  
  op_data_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.RobotBaseOp.op_data)
}

// -------------------------------------------------------------------

// RobotNavLocInfo

// double timestamp = 1;
inline void RobotNavLocInfo::clear_timestamp() {
  timestamp_ = 0;
}
inline double RobotNavLocInfo::timestamp() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.RobotNavLocInfo.timestamp)
  return timestamp_;
}
inline void RobotNavLocInfo::set_timestamp(double value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.RobotNavLocInfo.timestamp)
}

// sint32 nav_loc_state = 2;
inline void RobotNavLocInfo::clear_nav_loc_state() {
  nav_loc_state_ = 0;
}
inline ::google::protobuf::int32 RobotNavLocInfo::nav_loc_state() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.RobotNavLocInfo.nav_loc_state)
  return nav_loc_state_;
}
inline void RobotNavLocInfo::set_nav_loc_state(::google::protobuf::int32 value) {
  
  nav_loc_state_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.RobotNavLocInfo.nav_loc_state)
}

// int32 pos_x = 3;
inline void RobotNavLocInfo::clear_pos_x() {
  pos_x_ = 0;
}
inline ::google::protobuf::int32 RobotNavLocInfo::pos_x() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.RobotNavLocInfo.pos_x)
  return pos_x_;
}
inline void RobotNavLocInfo::set_pos_x(::google::protobuf::int32 value) {
  
  pos_x_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.RobotNavLocInfo.pos_x)
}

// int32 pos_y = 4;
inline void RobotNavLocInfo::clear_pos_y() {
  pos_y_ = 0;
}
inline ::google::protobuf::int32 RobotNavLocInfo::pos_y() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.RobotNavLocInfo.pos_y)
  return pos_y_;
}
inline void RobotNavLocInfo::set_pos_y(::google::protobuf::int32 value) {
  
  pos_y_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.RobotNavLocInfo.pos_y)
}

// int32 pos_z = 5;
inline void RobotNavLocInfo::clear_pos_z() {
  pos_z_ = 0;
}
inline ::google::protobuf::int32 RobotNavLocInfo::pos_z() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.RobotNavLocInfo.pos_z)
  return pos_z_;
}
inline void RobotNavLocInfo::set_pos_z(::google::protobuf::int32 value) {
  
  pos_z_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.RobotNavLocInfo.pos_z)
}

// int32 quat_x = 6;
inline void RobotNavLocInfo::clear_quat_x() {
  quat_x_ = 0;
}
inline ::google::protobuf::int32 RobotNavLocInfo::quat_x() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.RobotNavLocInfo.quat_x)
  return quat_x_;
}
inline void RobotNavLocInfo::set_quat_x(::google::protobuf::int32 value) {
  
  quat_x_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.RobotNavLocInfo.quat_x)
}

// int32 quat_y = 7;
inline void RobotNavLocInfo::clear_quat_y() {
  quat_y_ = 0;
}
inline ::google::protobuf::int32 RobotNavLocInfo::quat_y() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.RobotNavLocInfo.quat_y)
  return quat_y_;
}
inline void RobotNavLocInfo::set_quat_y(::google::protobuf::int32 value) {
  
  quat_y_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.RobotNavLocInfo.quat_y)
}

// int32 quat_z = 8;
inline void RobotNavLocInfo::clear_quat_z() {
  quat_z_ = 0;
}
inline ::google::protobuf::int32 RobotNavLocInfo::quat_z() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.RobotNavLocInfo.quat_z)
  return quat_z_;
}
inline void RobotNavLocInfo::set_quat_z(::google::protobuf::int32 value) {
  
  quat_z_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.RobotNavLocInfo.quat_z)
}

// int32 quat_w = 9;
inline void RobotNavLocInfo::clear_quat_w() {
  quat_w_ = 0;
}
inline ::google::protobuf::int32 RobotNavLocInfo::quat_w() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.RobotNavLocInfo.quat_w)
  return quat_w_;
}
inline void RobotNavLocInfo::set_quat_w(::google::protobuf::int32 value) {
  
  quat_w_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.RobotNavLocInfo.quat_w)
}

// int32 vel_x = 10;
inline void RobotNavLocInfo::clear_vel_x() {
  vel_x_ = 0;
}
inline ::google::protobuf::int32 RobotNavLocInfo::vel_x() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.RobotNavLocInfo.vel_x)
  return vel_x_;
}
inline void RobotNavLocInfo::set_vel_x(::google::protobuf::int32 value) {
  
  vel_x_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.RobotNavLocInfo.vel_x)
}

// int32 vel_y = 11;
inline void RobotNavLocInfo::clear_vel_y() {
  vel_y_ = 0;
}
inline ::google::protobuf::int32 RobotNavLocInfo::vel_y() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.RobotNavLocInfo.vel_y)
  return vel_y_;
}
inline void RobotNavLocInfo::set_vel_y(::google::protobuf::int32 value) {
  
  vel_y_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.RobotNavLocInfo.vel_y)
}

// int32 vel_z = 12;
inline void RobotNavLocInfo::clear_vel_z() {
  vel_z_ = 0;
}
inline ::google::protobuf::int32 RobotNavLocInfo::vel_z() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.RobotNavLocInfo.vel_z)
  return vel_z_;
}
inline void RobotNavLocInfo::set_vel_z(::google::protobuf::int32 value) {
  
  vel_z_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.RobotNavLocInfo.vel_z)
}

// int32 angular_x = 13;
inline void RobotNavLocInfo::clear_angular_x() {
  angular_x_ = 0;
}
inline ::google::protobuf::int32 RobotNavLocInfo::angular_x() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.RobotNavLocInfo.angular_x)
  return angular_x_;
}
inline void RobotNavLocInfo::set_angular_x(::google::protobuf::int32 value) {
  
  angular_x_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.RobotNavLocInfo.angular_x)
}

// int32 angular_y = 14;
inline void RobotNavLocInfo::clear_angular_y() {
  angular_y_ = 0;
}
inline ::google::protobuf::int32 RobotNavLocInfo::angular_y() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.RobotNavLocInfo.angular_y)
  return angular_y_;
}
inline void RobotNavLocInfo::set_angular_y(::google::protobuf::int32 value) {
  
  angular_y_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.RobotNavLocInfo.angular_y)
}

// int32 angular_z = 15;
inline void RobotNavLocInfo::clear_angular_z() {
  angular_z_ = 0;
}
inline ::google::protobuf::int32 RobotNavLocInfo::angular_z() const {
  // @@protoc_insertion_point(field_get:robot_base_msgs.RobotNavLocInfo.angular_z)
  return angular_z_;
}
inline void RobotNavLocInfo::set_angular_z(::google::protobuf::int32 value) {
  
  angular_z_ = value;
  // @@protoc_insertion_point(field_set:robot_base_msgs.RobotNavLocInfo.angular_z)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace robot_base_msgs

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_robot_5fbase_2frobot_5fbase_5fmsgs_2eproto
