// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_base/std_msgs.proto

#ifndef PROTOBUF_INCLUDED_robot_5fbase_2fstd_5fmsgs_2eproto
#define PROTOBUF_INCLUDED_robot_5fbase_2fstd_5fmsgs_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_robot_5fbase_2fstd_5fmsgs_2eproto 

namespace protobuf_robot_5fbase_2fstd_5fmsgs_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
}  // namespace protobuf_robot_5fbase_2fstd_5fmsgs_2eproto
namespace std_msgs {
class Header;
class HeaderDefaultTypeInternal;
extern HeaderDefaultTypeInternal _Header_default_instance_;
class TimeStamp;
class TimeStampDefaultTypeInternal;
extern TimeStampDefaultTypeInternal _TimeStamp_default_instance_;
}  // namespace std_msgs
namespace google {
namespace protobuf {
template<> ::std_msgs::Header* Arena::CreateMaybeMessage<::std_msgs::Header>(Arena*);
template<> ::std_msgs::TimeStamp* Arena::CreateMaybeMessage<::std_msgs::TimeStamp>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace std_msgs {

// ===================================================================

class TimeStamp : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:std_msgs.TimeStamp) */ {
 public:
  TimeStamp();
  virtual ~TimeStamp();

  TimeStamp(const TimeStamp& from);

  inline TimeStamp& operator=(const TimeStamp& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TimeStamp(TimeStamp&& from) noexcept
    : TimeStamp() {
    *this = ::std::move(from);
  }

  inline TimeStamp& operator=(TimeStamp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const TimeStamp& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TimeStamp* internal_default_instance() {
    return reinterpret_cast<const TimeStamp*>(
               &_TimeStamp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(TimeStamp* other);
  friend void swap(TimeStamp& a, TimeStamp& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TimeStamp* New() const final {
    return CreateMaybeMessage<TimeStamp>(NULL);
  }

  TimeStamp* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<TimeStamp>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const TimeStamp& from);
  void MergeFrom(const TimeStamp& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(TimeStamp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 nanos = 2;
  void clear_nanos();
  static const int kNanosFieldNumber = 2;
  ::google::protobuf::uint64 nanos() const;
  void set_nanos(::google::protobuf::uint64 value);

  // int32 secs = 1;
  void clear_secs();
  static const int kSecsFieldNumber = 1;
  ::google::protobuf::int32 secs() const;
  void set_secs(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:std_msgs.TimeStamp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::uint64 nanos_;
  ::google::protobuf::int32 secs_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_robot_5fbase_2fstd_5fmsgs_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Header : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:std_msgs.Header) */ {
 public:
  Header();
  virtual ~Header();

  Header(const Header& from);

  inline Header& operator=(const Header& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Header(Header&& from) noexcept
    : Header() {
    *this = ::std::move(from);
  }

  inline Header& operator=(Header&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const Header& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Header* internal_default_instance() {
    return reinterpret_cast<const Header*>(
               &_Header_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(Header* other);
  friend void swap(Header& a, Header& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Header* New() const final {
    return CreateMaybeMessage<Header>(NULL);
  }

  Header* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Header>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const Header& from);
  void MergeFrom(const Header& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Header* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string frame_id = 2;
  void clear_frame_id();
  static const int kFrameIdFieldNumber = 2;
  const ::std::string& frame_id() const;
  void set_frame_id(const ::std::string& value);
  #if LANG_CXX11
  void set_frame_id(::std::string&& value);
  #endif
  void set_frame_id(const char* value);
  void set_frame_id(const char* value, size_t size);
  ::std::string* mutable_frame_id();
  ::std::string* release_frame_id();
  void set_allocated_frame_id(::std::string* frame_id);

  // .std_msgs.TimeStamp stamp = 1;
  bool has_stamp() const;
  void clear_stamp();
  static const int kStampFieldNumber = 1;
  private:
  const ::std_msgs::TimeStamp& _internal_stamp() const;
  public:
  const ::std_msgs::TimeStamp& stamp() const;
  ::std_msgs::TimeStamp* release_stamp();
  ::std_msgs::TimeStamp* mutable_stamp();
  void set_allocated_stamp(::std_msgs::TimeStamp* stamp);

  // @@protoc_insertion_point(class_scope:std_msgs.Header)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr frame_id_;
  ::std_msgs::TimeStamp* stamp_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_robot_5fbase_2fstd_5fmsgs_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TimeStamp

// int32 secs = 1;
inline void TimeStamp::clear_secs() {
  secs_ = 0;
}
inline ::google::protobuf::int32 TimeStamp::secs() const {
  // @@protoc_insertion_point(field_get:std_msgs.TimeStamp.secs)
  return secs_;
}
inline void TimeStamp::set_secs(::google::protobuf::int32 value) {
  
  secs_ = value;
  // @@protoc_insertion_point(field_set:std_msgs.TimeStamp.secs)
}

// uint64 nanos = 2;
inline void TimeStamp::clear_nanos() {
  nanos_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 TimeStamp::nanos() const {
  // @@protoc_insertion_point(field_get:std_msgs.TimeStamp.nanos)
  return nanos_;
}
inline void TimeStamp::set_nanos(::google::protobuf::uint64 value) {
  
  nanos_ = value;
  // @@protoc_insertion_point(field_set:std_msgs.TimeStamp.nanos)
}

// -------------------------------------------------------------------

// Header

// .std_msgs.TimeStamp stamp = 1;
inline bool Header::has_stamp() const {
  return this != internal_default_instance() && stamp_ != NULL;
}
inline void Header::clear_stamp() {
  if (GetArenaNoVirtual() == NULL && stamp_ != NULL) {
    delete stamp_;
  }
  stamp_ = NULL;
}
inline const ::std_msgs::TimeStamp& Header::_internal_stamp() const {
  return *stamp_;
}
inline const ::std_msgs::TimeStamp& Header::stamp() const {
  const ::std_msgs::TimeStamp* p = stamp_;
  // @@protoc_insertion_point(field_get:std_msgs.Header.stamp)
  return p != NULL ? *p : *reinterpret_cast<const ::std_msgs::TimeStamp*>(
      &::std_msgs::_TimeStamp_default_instance_);
}
inline ::std_msgs::TimeStamp* Header::release_stamp() {
  // @@protoc_insertion_point(field_release:std_msgs.Header.stamp)
  
  ::std_msgs::TimeStamp* temp = stamp_;
  stamp_ = NULL;
  return temp;
}
inline ::std_msgs::TimeStamp* Header::mutable_stamp() {
  
  if (stamp_ == NULL) {
    auto* p = CreateMaybeMessage<::std_msgs::TimeStamp>(GetArenaNoVirtual());
    stamp_ = p;
  }
  // @@protoc_insertion_point(field_mutable:std_msgs.Header.stamp)
  return stamp_;
}
inline void Header::set_allocated_stamp(::std_msgs::TimeStamp* stamp) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete stamp_;
  }
  if (stamp) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      stamp = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, stamp, submessage_arena);
    }
    
  } else {
    
  }
  stamp_ = stamp;
  // @@protoc_insertion_point(field_set_allocated:std_msgs.Header.stamp)
}

// string frame_id = 2;
inline void Header::clear_frame_id() {
  frame_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Header::frame_id() const {
  // @@protoc_insertion_point(field_get:std_msgs.Header.frame_id)
  return frame_id_.GetNoArena();
}
inline void Header::set_frame_id(const ::std::string& value) {
  
  frame_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:std_msgs.Header.frame_id)
}
#if LANG_CXX11
inline void Header::set_frame_id(::std::string&& value) {
  
  frame_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:std_msgs.Header.frame_id)
}
#endif
inline void Header::set_frame_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  frame_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:std_msgs.Header.frame_id)
}
inline void Header::set_frame_id(const char* value, size_t size) {
  
  frame_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:std_msgs.Header.frame_id)
}
inline ::std::string* Header::mutable_frame_id() {
  
  // @@protoc_insertion_point(field_mutable:std_msgs.Header.frame_id)
  return frame_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Header::release_frame_id() {
  // @@protoc_insertion_point(field_release:std_msgs.Header.frame_id)
  
  return frame_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Header::set_allocated_frame_id(::std::string* frame_id) {
  if (frame_id != NULL) {
    
  } else {
    
  }
  frame_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), frame_id);
  // @@protoc_insertion_point(field_set_allocated:std_msgs.Header.frame_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace std_msgs

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_robot_5fbase_2fstd_5fmsgs_2eproto
